{
  "login": "github-actions[bot]",
  "id": 41898282,
  "node_id": "MDM6Qm90NDE4OTgyODI=",
  "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/github-actions%5Bbot%5D",
  "html_url": "https://github.com/apps/github-actions",
  "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
  "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
  "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
  "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
  "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
  "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
  "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
  "type": "Bot",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 0,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2018-07-30T09:30:16Z",
  "updated_at": "2018-09-18T23:02:41Z"
}
